### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by EtienneBruines** [EngoEngine/engoengine.github.io#11]
Is our logo final? If so, let's add it to our website header! 

I think it should be added within the `_includes/header.html` file.

**Comment by paked** [comment]
:+1:

**Comment by paked** [comment]
URL for image is here: http://imgur.com/hb25tl6

**Comment by paked** [comment]
I personally think that we should only have it on the main page, in order to save space.

**Comment by EtienneBruines** [comment]
![](https://www.huperwebs.nl/upload/screenshot-2016-04-25_20:24:56.jpg)
