### ISSUE TITLE
Add link to GoDoc.org

### ISSUE THREAD

**Issue by mewmew** [EngoEngine/engoengine.github.io#21]
We should make sure to add links to GoDoc.org
- https://godoc.org/engo.io/ecs
- https://godoc.org/engo.io/engo
- https://godoc.org/engo.io/engo/core

Based on the discussion at https://gitter.im/EngoEngine/engo?at=57240e47e10a59c0610750d4

> > > @otraore
> > > I also think before v1 we need a site redesign
> > 
> > @mewmew
> > With or without a site redesign, it would be great if there was a link to GoDoc.org from engo.io. Perhaps there is one and I failed to find it?
> 
> @otraore 
> I don’t think there is but I do agree there should be one

**Comment by Noofbiz** [comment]
Fixed by #28
