### ISSUE TITLE
Remove webgl import path

### ISSUE THREAD

**Issue by otraore** [EngoEngine/engoengine.github.io#22]
The webgl package has been deprecated for a while so i think it's about time we remove it from this site. It has no use here.

**Comment by paked** [comment]
We can remove `vendor/*` as well.

**Comment by otraore** [comment]
Sounds good, sending a pr

**Comment by otraore** [comment]
Fixed by https://github.com/EngoEngine/engoengine.github.io/commit/5b4b9d257be7d069b7294408b4fbdecb0d17ca28 and https://github.com/EngoEngine/engoengine.github.io/commit/9ecad63cdff4d30d66ee74e95c1270f553bf33ad respectively.
