### ISSUE TITLE
Tutorial needs a note to check out v1.0 of ecs

### ISSUE THREAD

**Issue by benabineri** [EngoEngine/engoengine.github.io#52]
Hi,

I'm working through the tutorial and I found that when I got to the end of 01-hello-world, I was encountering the following error:

```
$ go run traffic.go
# engo.io/engo/common
../../../engo.io/engo/common/animation.go:99:11: invalid map key type ecs.BasicEntity
../../../engo.io/engo/common/animation.go:110:21: invalid map key type ecs.BasicEntity
```

After a bit of thinking and fiddling, I ran:

```
$ cd /src/engo.io/ecs/
$ git checkout v1.0
```

Changing back to the TrafficManager directory and running `go run` worked.

(Apologies for not raising a PR to fix the doc but I wasn't sure about the best place to put a note about this. In the foreword?)

**Comment by Noofbiz** [comment]
Thanks for finding that! I'll be fixed shortly!
