### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by waveletlet** [EngoEngine/engoengine.github.io#54]
engo.io currently seems to be a domain squatter.

**Comment by Noofbiz** [comment]
Yeah, we're working on getting in contact with the owner of the domain. There's an issue [here](https://github.com/EngoEngine/engo/issues/528) too. Sorry for any inconvenience!

**Comment by paked** [comment]
(closing as this issue has been resolved, move all further discussion to https://github.com/EngoEngine/engo/issues/528)
